# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - uses: actions/setup-node@v3
        
    - run: npm ci
    
    - name: Run Prisma Migration
      run: npm run migrate:deploy
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.API_KEY }}
        heroku_email: ${{ secrets.EMAIL }}
        heroku_app_name: ${{ secrets.APP_NAME }}
        
